service:
  name: serverless-coldstart-benchmarking

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: src/handlers/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

  custom:
    handler: src/handlers/custom.handler
    events:
      - http:
          method: GET
          path: /custom